import React, { useEffect, useState } from 'react';
import { Link } from 'react-router-dom';
import { motion } from 'motion/react';
import { 
  Megaphone, Target, Layers, ArrowRight, Sparkles, 
  Globe, Share2, CheckCircle2, MessageSquare, TrendingUp, 
  PenTool, LayoutTemplate, Search, Loader2, Zap, BarChart, ChevronRight, Calendar,
  X, XCircle, Bot, ZapOff, Fingerprint, Database, CalendarDays, Radar, Activity, Cpu, Network, BrainCircuit, Palette, Send
} from 'lucide-react';
import { ImmersiveHero } from '../components/ImmersiveHero';

// ------------------------------------------
// HIGH-FIDELITY APP MOCKUPS (Using pure HTML/CSS/Tailwind)
// ------------------------------------------

const HeroDashboardMockup = () => (
  <motion.div 
    initial={{ opacity: 0, y: 40 }}
    animate={{ opacity: 1, y: 0 }}
    transition={{ duration: 0.8, delay: 0.4 }}
    className="w-full max-w-6xl mx-auto rounded-xl border border-white/10 bg-[#0F0F16] shadow-[0_20px_70px_rgba(124,58,237,0.15)] overflow-hidden flex flex-col md:flex-row h-[350px] md:h-[450px] mt-16 relative"
  >
    {/* Sidebar */}
    <div className="w-16 md:w-56 border-r border-white/10 bg-[#0A0A0F]/80 p-4 flex flex-col gap-6 shrink-0 z-10">
      <div className="flex items-center gap-2 mb-2">
        <div className="w-8 h-8 rounded-lg bg-[#7C3AED] p-[1px]">
          <div className="w-full h-full bg-[#1C1C22] rounded-[7px] flex items-center justify-center">
            <img src="https://darkgray-finch-838850.hostingersite.com/wp-content/uploads/2026/04/B2PLOGO.png" alt="Logo" className="w-5 h-5 object-contain" />
          </div>
        </div>
        <div className="hidden md:block h-3 w-20 bg-white/10 rounded-sm"></div>
      </div>
      <div className="space-y-3">
        <div className="flex items-center gap-3 px-2 py-2 rounded-lg bg-white/5 border border-white/10">
          <Target className="w-4 h-4 text-[#7C3AED]" />
          <div className="hidden md:block h-2 w-16 bg-[#7C3AED]/40 rounded-sm"></div>
        </div>
        <div className="flex items-center gap-3 px-2 py-2 rounded-lg opacity-50">
          <Layers className="w-4 h-4 text-white" />
          <div className="hidden md:block h-2 w-20 bg-white/30 rounded-sm"></div>
        </div>
        <div className="flex items-center gap-3 px-2 py-2 rounded-lg opacity-50">
          <CalendarDays className="w-4 h-4 text-white" />
          <div className="hidden md:block h-2 w-14 bg-white/30 rounded-sm"></div>
        </div>
      </div>
    </div>
    
    {/* Main View: Week Schedule */}
    <div className="flex-1 p-4 md:p-8 relative bg-[#0A0A0F] overflow-hidden flex flex-col">
      <div className="flex justify-between items-end border-b border-white/10 pb-4 mb-6 shrink-0">
        <div>
          <h3 className="text-white font-display font-medium text-lg md:text-xl flex items-center gap-2">
            Q4 Product Launch <span className="bg-[#18F07A]/10 text-[#18F07A] text-[10px] px-2 py-0.5 rounded-full border border-[#18F07A]/20">Active</span>
          </h3>
          <p className="text-xs text-gray-400 mt-1">Generated by Tror in 2m 43s</p>
        </div>
        <div className="hidden md:flex gap-2">
          <div className="h-8 w-8 rounded-lg bg-white/5 flex items-center justify-center border border-white/10"><Share2 className="w-3.5 h-3.5 text-gray-400" /></div>
          <div className="h-8 px-4 rounded-lg bg-[#7C3AED] flex items-center text-xs font-medium text-white shadow-lg">Approve Week</div>
        </div>
      </div>
      
      {/* Cards Grid */}
      <div className="grid grid-cols-1 md:grid-cols-3 gap-4 flex-1">
         {/* Mon */}
         <div className="bg-[#1C1C22]/80 border border-white/10 rounded-xl p-4 flex flex-col relative overflow-hidden group hover:border-[#7C3AED]/50 transition-colors">
            <div className="text-[10px] font-medium text-gray-400 uppercase tracking-wider mb-3 flex justify-between">Mon, Oct 12 <div className="w-2 h-2 rounded-full bg-[#0A66C2]"></div></div>
            <div className="flex gap-2 mb-3">
               <span className="text-[9px] bg-white/10 px-1.5 py-0.5 rounded text-white flex gap-1 items-center"><Target className="w-2.5 h-2.5"/> Education</span>
            </div>
            <div className="space-y-2 flex-1">
              <div className="h-2 w-full bg-white/10 rounded"></div>
              <div className="h-2 w-full bg-white/10 rounded"></div>
              <div className="h-2 w-3/4 bg-white/10 rounded"></div>
            </div>
            <div className="mt-4 pt-3 border-t border-white/10 flex justify-between items-center text-[10px]">
               <span className="text-[#0A66C2] font-semibold bg-[#0A66C2]/10 px-2 py-1 rounded">LinkedIn</span>
               <span className="text-gray-500">Scheduled 9:00 AM</span>
            </div>
         </div>
         {/* Wed */}
         <div className="bg-[#1C1C22]/80 border border-white/10 rounded-xl p-4 flex flex-col relative overflow-hidden group hover:border-[#7C3AED]/50 transition-colors hidden sm:flex">
            <div className="text-[10px] font-medium text-gray-400 uppercase tracking-wider mb-3 flex justify-between">Wed, Oct 14 <div className="w-2 h-2 rounded-full bg-black border border-white/20"></div></div>
            <div className="flex gap-2 mb-3">
               <span className="text-[9px] bg-white/10 px-1.5 py-0.5 rounded text-white flex gap-1 items-center"><TrendingUp className="w-2.5 h-2.5"/> Engagement</span>
            </div>
            <div className="space-y-2 flex-1">
              <div className="h-2 w-full bg-white/10 rounded"></div>
              <div className="h-2 w-2/3 bg-white/10 rounded"></div>
            </div>
            <div className="mt-4 pt-3 border-t border-white/10 flex justify-between items-center text-[10px]">
               <span className="text-white font-semibold bg-white/10 px-2 py-1 rounded">X (Twitter)</span>
               <span className="text-gray-500">Scheduled 1:30 PM</span>
            </div>
         </div>
         {/* Fri */}
         <div className="bg-[#1C1C22]/80 border border-white/10 rounded-xl p-4 flex flex-col relative overflow-hidden group hover:border-[#7C3AED]/50 transition-colors hidden md:flex">
            <div className="text-[10px] font-medium text-gray-400 uppercase tracking-wider mb-3 flex justify-between">Fri, Oct 16 <div className="w-2 h-2 rounded-full bg-[#7C3AED]"></div></div>
            <div className="w-full h-24 bg-white/5 rounded-lg mb-3 border border-white/10 flex items-center justify-center">
               <div className="w-8 h-8 rounded bg-white/10"></div>
            </div>
            <div className="space-y-2 flex-1 mt-auto">
              <div className="h-2 w-full bg-white/10 rounded"></div>
              <div className="h-2 w-1/2 bg-white/10 rounded"></div>
            </div>
            <div className="mt-4 pt-3 border-t border-white/10 flex justify-between items-center text-[10px]">
               <span className="text-pink-400 font-semibold bg-pink-500/10 px-2 py-1 rounded">Instagram</span>
               <span className="text-gray-500">Scheduled 4:00 PM</span>
            </div>
         </div>
      </div>
    </div>
  </motion.div>
);

const TrorCommandCenterMockup = () => (
  <div className="w-full max-w-2xl mx-auto h-[480px] bg-[#0A0A0F]/90 backdrop-blur-2xl border border-[#2583EB]/30 rounded-2xl shadow-[0_20px_70px_rgba(37,131,235,0.15)] overflow-hidden flex flex-col relative group">
    {/* Dynamic Background Effect */}
    <div className="absolute inset-0 bg-[#2583EB]/[0.02] pointer-events-none"></div>
    
    {/* Header */}
    <div className="h-16 border-b border-white/10 bg-[#1C1C22]/80 flex flex-col sm:flex-row sm:items-center justify-between px-6 shrink-0 relative z-10 gap-2 sm:gap-0 justify-center sm:justify-between py-2 sm:py-0">
      <div className="flex items-center gap-4">
        <div className="relative">
          <img src="https://darkgray-finch-838850.hostingersite.com/wp-content/uploads/2026/04/B2P-AVATAR.png" className="w-10 h-10 rounded-full border border-[#2583EB] shadow-[0_0_15px_rgba(37,131,235,0.5)]" alt="Tror" />
          <div className="absolute bottom-0 -right-1 w-3.5 h-3.5 bg-[#18F07A] rounded-full border-2 border-[#1C1C22] shadow-[0_0_8px_rgba(24,240,122,0.8)]"></div>
        </div>
        <div>
          <h4 className="text-white font-medium text-sm tracking-tight flex items-center gap-2">TROR <span className="bg-[#2583EB]/20 border border-[#2583EB]/30 text-[#2583EB] text-[9px] px-1.5 py-0.5 rounded font-mono shadow-[0_0_10px_rgba(37,131,235,0.2)] inset-shadow-inner text-shadow-sm">SYS_ADMIN</span></h4>
          <div className="text-[10px] text-gray-400 font-mono flex items-center gap-1 mt-0.5"><div className="w-1.5 h-1.5 bg-[#18F07A] rounded-full animate-pulse"></div> ACTIVE IN COMMAND CENTER</div>
        </div>
      </div>
      <div className="flex items-center gap-4 text-[10px] font-mono text-gray-400 hidden sm:flex">
        <span className="flex items-center gap-1"><Activity className="w-3.5 h-3.5 text-[#18F07A]" /> 99.9% UPTIME</span>
        <span className="flex items-center gap-1"><Cpu className="w-3.5 h-3.5 text-[#7C3AED]" /> NEURAL NET</span>
      </div>
    </div>
    
    {/* Body */}
    <div className="flex-1 flex flex-col sm:flex-row p-4 sm:p-6 gap-4 sm:gap-6 overflow-hidden relative">
      
      {/* Analytics Nodes (Left Column) */}
      <div className="w-full sm:w-1/3 flex flex-row sm:flex-col justify-between sm:justify-start relative z-10 gap-3">
        {/* Memory Node */}
        <div className="flex-1 sm:flex-none bg-[#1C1C22] border border-white/10 rounded-xl p-3 shrink-0 hover:border-[#7C3AED]/50 transition-colors shadow-lg">
          <div className="flex items-center gap-2 text-[#7C3AED] text-[11px] font-medium uppercase tracking-wider mb-2">
            <Database className="w-3.5 h-3.5" /> DNA Integrity
          </div>
          <div className="space-y-2">
            <div className="flex justify-between text-[10px] text-gray-400"><span>Positioning Match</span> <span className="text-[#18F07A] font-medium text-[9px]">100%</span></div>
            <div className="w-full h-1.5 bg-white/5 rounded-full overflow-hidden border border-white/10"><motion.div initial={{ width: "0%" }} whileInView={{ width: "100%" }} transition={{ duration: 1.5, ease: "easeOut" }} className="h-full bg-[#7C3AED] shadow-[0_0_10px_rgba(24,240,122,0.5)]"></motion.div></div>
          </div>
        </div>
        
        {/* Intel Node */}
        <div className="flex-1 sm:flex-none bg-[#1C1C22] border border-white/10 rounded-xl p-3 shrink-0 hover:border-[#2583EB]/50 transition-colors shadow-lg">
          <div className="flex items-center gap-2 text-[#2583EB] text-[11px] font-medium uppercase tracking-wider mb-2">
            <Radar className="w-3.5 h-3.5" /> Live Intel Stream
          </div>
          <div className="text-[10px] text-gray-400 space-y-1.5 font-mono">
            <div className="flex items-start gap-1.5"><div className="w-1.5 h-1.5 rounded-full bg-yellow-500 mt-1 shrink-0"></div> <span className="line-clamp-1 border-b border-white/5 pb-0.5">Scraping LinkedIn feeds...</span></div>
            <div className="flex items-start gap-1.5"><div className="w-1.5 h-1.5 rounded-full bg-[#18F07A] mt-1 shrink-0 shadow-[0_0_5px_rgba(24,240,122,0.8)]"></div> <span className="line-clamp-1 border-b border-white/5 pb-0.5 text-white/80">Analyzed 12 competitor posts.</span></div>
            <div className="flex items-start gap-1.5"><div className="w-1.5 h-1.5 rounded-full bg-yellow-500 mt-1 shrink-0"></div> <span className="line-clamp-1">Monitoring Substack trends...</span></div>
          </div>
        </div>
      </div>
      
      {/* Central Execution Interface (Right Column) */}
      <div className="flex-1 bg-[#0A0A0F]/80 border border-[#2583EB]/30 rounded-xl p-4 flex flex-col relative shadow-[inset_0_0_50px_rgba(37,131,235,0.05)] overflow-hidden">
         <div className="absolute top-3 right-4 text-[#2583EB] text-[10px] font-mono animate-pulse flex items-center gap-1.5">
           <Network className="w-3 h-3" /> EXECUTING ROUTINE
         </div>
         
         <div className="h-full flex flex-col justify-end space-y-3 relative z-10 font-mono text-xs pb-1">
            <motion.div initial={{ opacity: 0, x: -10 }} whileInView={{ opacity: 1, x: 0 }} transition={{ delay: 0.2 }} className="text-gray-500 flex items-center gap-2">
              <span className="text-[#9D5CFF]">$&gt;</span> initializing autonomous campaign build...
            </motion.div>
            <motion.div initial={{ opacity: 0, x: -10 }} whileInView={{ opacity: 1, x: 0 }} transition={{ delay: 0.6 }} className="text-[#2583EB] flex items-center gap-2 font-semibold">
              <span className="text-[#9D5CFF]">$&gt;</span> Identifying narrative counter-angle...
            </motion.div>
            <motion.div initial={{ opacity: 0 }} whileInView={{ opacity: 1 }} transition={{ delay: 1 }} className="text-gray-400 pl-4 border-l border-[#2583EB]/30 ml-2 space-y-1.5 py-1">
              <div className="flex items-center gap-2"><div className="w-1 h-1 bg-[#2583EB] rounded-full"></div> Applying Tone: <span className="text-white/80 bg-white/10 px-1 rounded">Challenger</span></div>
              <div className="flex items-center gap-2"><div className="w-1 h-1 bg-[#2583EB] rounded-full"></div> Drafting <span className="text-white/80">LinkedIn Carousel / X Thread / LI Post</span></div>
            </motion.div>
            <motion.div initial={{ opacity: 0, x: -10 }} whileInView={{ opacity: 1, x: 0 }} transition={{ delay: 1.5 }} className="text-[#18F07A] flex items-center gap-2 font-medium bg-[#18F07A]/10 px-2 py-1.5 rounded-md border border-[#18F07A]/20">
              <span className="text-[#18F07A]">$&gt;</span> GENERATION COMPLETE [6 ASSETS] <CheckCircle2 className="w-3.5 h-3.5" />
            </motion.div>
            
            <motion.div initial={{ opacity: 0, y: 10 }} whileInView={{ opacity: 1, y: 0 }} transition={{ delay: 2 }} className="mt-4 bg-[#1C1C22] border border-[#2583EB]/40 rounded-lg p-3 sm:p-4 text-white font-sans text-sm border-l-4 border-l-[#2583EB] shadow-lg relative cursor-default hover:border-[#2583EB] transition-colors group">
               <div className="absolute top-2 right-2 opacity-0 group-hover:opacity-100 transition-opacity flex gap-1">
                  <div className="bg-white/10 p-1 rounded hover:bg-white/20"><Search className="w-3 h-3 text-white"/></div>
               </div>
               <div className="font-medium mb-2 flex items-center gap-2 text-xs text-gray-300 uppercase tracking-wider"><Bot className="w-3 h-3 text-[#2583EB]" /> Output Preview</div>
               <p className="text-sm font-medium leading-relaxed italic text-gray-200">
                 "Everybody assumes scaling operations means hiring more SDRs. The math on that breaks exactly at $5M ARR. Here is the operational engine that actually gets you to $10M."
               </p>
            </motion.div>
         </div>
      </div>
      
    </div>
  </div>
);

// ------------------------------------------
// MAIN COMPONENT
// ------------------------------------------

export function LandingPage() {
  const [isScrolled, setIsScrolled] = useState(false);
  const [whatsappUrl, setWhatsappUrl] = useState("/whatsapp/login");
  const [isDefaultWhatsAppUrl, setIsDefaultWhatsAppUrl] = useState(true);
  const [showSetupModal, setShowSetupModal] = useState(false);
  const [botPhoneNumberInput, setBotPhoneNumberInput] = useState("");
  const [isLinking, setIsLinking] = useState(false);
  const [linkSuccess, setLinkSuccess] = useState(false);
  const [linkError, setLinkError] = useState("");

  useEffect(() => {
    const handleScroll = () => setIsScrolled(window.scrollY > 30);
    window.addEventListener('scroll', handleScroll, { passive: true });

    // Fetch dynamic onboarding WhatsApp deep-link
    fetch('/api/whatsapp/public-link')
      .then(res => res.json())
      .then(data => {
        if (data.url) {
          setWhatsappUrl(data.url);
        }
        setIsDefaultWhatsAppUrl(!!data.isDefault);
      })
      .catch(err => {
        console.error("Failed to load WhatsApp link", err);
        setIsDefaultWhatsAppUrl(true);
      });

    return () => window.removeEventListener('scroll', handleScroll);
  }, []);

  const handleQuickSetupInput = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!botPhoneNumberInput.trim()) {
      setLinkError("Please enter your WhatsApp bot number first.");
      return;
    }
    const cleanNum = botPhoneNumberInput.replace(/\D/g, '');
    if (!cleanNum || cleanNum.length < 8) {
      setLinkError("Invalid formatting. Please enter numbers containing your country code.");
      return;
    }

    setIsLinking(true);
    setLinkError("");
    try {
      const response = await fetch('/api/whatsapp/quick-setup-number', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ botPhoneNumber: cleanNum })
      });
      const data = await response.json();
      if (!response.ok) {
        throw new Error(data.error || "Failed to link number. Please make sure your server is running.");
      }
      setWhatsappUrl(data.url);
      setIsDefaultWhatsAppUrl(false);
      setLinkSuccess(true);
      setTimeout(() => {
        setShowSetupModal(false);
        setLinkSuccess(false);
        setBotPhoneNumberInput("");
        // Instantly launch!
        window.open(data.url, '_blank');
      }, 1500);
    } catch (err: any) {
      setLinkError(err.message || "An unexpected error occurred.");
    } finally {
      setIsLinking(false);
    }
  };

  return (
    <div className="min-h-screen bg-[#0A0A0F] text-[#F7F7F8] font-sans selection:bg-[#7C3AED]/30 selection:text-white overflow-x-hidden relative">
      <nav className={`fixed top-0 left-0 right-0 z-50 transition-all duration-300 ${isScrolled ? 'bg-[#0A0A0F]/80 border-b border-white/5 py-4 backdrop-blur-xl shadow-lg' : 'bg-transparent py-6'}`}>
        <div className="max-w-7xl mx-auto px-6 lg:px-8">
          <div className="flex justify-between items-center">
            <div className="flex items-center gap-3 group shrink-0">
              <div className="w-8 h-8 rounded-lg bg-[#7C3AED] p-[1px] shadow-[0_0_15px_rgba(124,58,237,0.3)]">
                <div className="w-full h-full bg-[#1C1C22] rounded-[7px] flex items-center justify-center">
                  <img src="https://darkgray-finch-838850.hostingersite.com/wp-content/uploads/2026/04/B2PLOGO.png" alt="Logo" className="w-5 h-5 object-contain" />
                </div>
              </div>
              <span className="text-xl tracking-tight font-display text-white font-medium">BrandToPost</span>
            </div>
            <div className="flex items-center gap-4 sm:gap-6">
              <Link to="/whatsapp/login" className="text-sm font-semibold text-emerald-400 hover:text-emerald-300 transition-colors flex items-center gap-1">
                <span className="w-2 h-2 rounded-full bg-emerald-400 animate-pulse inline-block"></span> WhatsApp Bot
              </Link>
              <Link to="/login" className="text-sm font-semibold text-gray-400 hover:text-white transition-colors hidden md:block">Sign In</Link>
              <Link to="/login" className="px-5 py-2.5 rounded-full text-sm font-medium transition-all hover:scale-105 active:scale-95 bg-white text-black shadow-[0_0_20px_rgba(255,255,255,0.1)] whitespace-nowrap">
                Start Free Trial
              </Link>
            </div>
          </div>
        </div>
      </nav>

      {/* Hero Section */}
      <ImmersiveHero 
        whatsappUrl={whatsappUrl} 
        isDefaultLink={isDefaultWhatsAppUrl} 
        onConfigureClick={() => setShowSetupModal(true)} 
      />

      {/* Metrics Strip */}
      <section className="py-12 border-y border-white/5 bg-[#1C1C22]/30 backdrop-blur-sm relative z-10">
        <div className="max-w-7xl mx-auto px-6 lg:px-8">
          <div className="grid grid-cols-2 md:grid-cols-4 gap-8 text-center divide-x-0 md:divide-x divide-white/10">
            <div className="flex flex-col items-center">
               <div className="text-3xl md:text-4xl font-normal text-white font-display mb-1">0</div>
               <div className="text-xs text-gray-400 font-medium uppercase tracking-wider">Prompts Required</div>
            </div>
            <div className="flex flex-col items-center">
               <div className="text-3xl md:text-4xl font-normal text-white font-display mb-1">100%</div>
               <div className="text-xs text-gray-400 font-medium uppercase tracking-wider">Brand DNA Retention</div>
            </div>
            <div className="flex flex-col items-center">
               <div className="text-3xl md:text-4xl font-normal text-white font-display mb-1 text-[#18F07A]">&lt; 3m</div>
               <div className="text-xs text-gray-400 font-medium uppercase tracking-wider">To Generate A Week</div>
            </div>
            <div className="flex flex-col items-center">
               <div className="text-3xl md:text-4xl font-normal text-white font-display mb-1">5+</div>
               <div className="text-xs text-gray-400 font-medium uppercase tracking-wider">Native Platforms</div>
            </div>
          </div>
        </div>
      </section>

{/* The Difference (Comparison) */}
      <section className="py-24 md:py-32 px-6 lg:px-8 max-w-7xl mx-auto relative z-10">
        <div className="text-center mb-16">
          <h2 className="text-4xl md:text-6xl font-normal font-display text-white mb-4">Diagnosing the struggle: The "AI Writer" illusion.</h2>
          <p className="text-lg text-gray-400 max-w-2xl mx-auto font-medium">You thought AI would save you time. Instead, you're spending hours writing prompts, correcting hallucinations, and playing copy-paste between ChatGPT, Canva, and your scheduler.</p>
        </div>

        <div className="grid grid-cols-1 md:grid-cols-2 gap-8 md:gap-12">
          {/* Generic AI Side */}
          <div className="bg-[#1C1C22]/40 border border-red-500/20 rounded-3xl p-8 lg:p-10 relative overflow-hidden">
            <div className="absolute top-0 right-0 p-4"><XCircle className="w-8 h-8 text-red-500/30" /></div>
            <h3 className="text-2xl font-medium text-white mb-8 flex items-center gap-3"><Bot className="w-6 h-6 text-gray-400"/> The Manual Chatbot Grind</h3>
            <ul className="space-y-6">
              <li className="flex gap-4 text-red-200/70 text-base">
                <ZapOff className="w-6 h-6 shrink-0 text-red-500 mt-1" />
                <span><span className="font-medium text-white">Endless Prompting:</span> You must constantly remind it: "Act like a B2B SaaS marketer targeting C-level execs. Make sure to sound bold."</span>
              </li>
              <li className="flex gap-4 text-red-200/70 text-base">
                <ZapOff className="w-6 h-6 shrink-0 text-red-500 mt-1" />
                <span><span className="font-medium text-white">Manual Formatting:</span> Generates one block of text. You have to copy, paste, and adapt it manually for a Twitter thread vs LinkedIn post.</span>
              </li>
              <li className="flex gap-4 text-red-200/70 text-base">
                <ZapOff className="w-6 h-6 shrink-0 text-red-500 mt-1" />
                <span><span className="font-medium text-white">Cliche Output:</span> Sounds robotic, polite, and completely devoid of point-of-view ("In today's fast-paced digital world...").</span>
              </li>
            </ul>
          </div>

          {/* B2P Side */}
          <div className="bg-[#1C1C22]/95 border border-[#7C3AED]/30 rounded-3xl p-8 lg:p-10 relative overflow-hidden shadow-[0_0_80px_rgba(124,58,237,0.15)]">
            <div className="absolute top-0 right-0 p-4"><div className="bg-[#7C3AED]/20 text-[#7C3AED] text-xs font-medium px-3 py-1.5 rounded-full border border-[#7C3AED]/30">The Autonomous Way</div></div>
            <h3 className="text-2xl font-medium text-white mb-8 flex items-center gap-3"><Zap className="w-6 h-6 text-[#7C3AED] fill-[#7C3AED]/20"/> The Autonomous Event Horizon</h3>
            <ul className="space-y-6">
              <li className="flex gap-4 text-gray-200 text-base font-medium">
                <CheckCircle2 className="w-6 h-6 shrink-0 text-[#18F07A] mt-1" />
                <span><span className="font-medium text-white">A Team, Not a Tool:</span> You don't type instructions; you give a URL. Tror and his agents handle the research, ideation, drafting, design, and scheduling concurrently.</span>
              </li>
              <li className="flex gap-4 text-gray-200 text-base font-medium">
                <CheckCircle2 className="w-6 h-6 shrink-0 text-[#18F07A] mt-1" />
                <span><span className="font-medium text-white">Multi-Format Architecture:</span> One campaign idea securely splits into native structures (e.g. a 5-part X Thread and a LinkedIn Carousel) simultaneously.</span>
              </li>
              <li className="flex gap-4 text-gray-200 text-base font-medium">
                <CheckCircle2 className="w-6 h-6 shrink-0 text-[#18F07A] mt-1" />
                <span><span className="font-medium text-white">Direct Scheduling:</span> Skip the messy spreadsheets. Approve the week directly in the interface and B2P pushes to platforms automatically.</span>
              </li>
            </ul>
          </div>
        </div>
      </section>

      


      {/* Psychographic Deep Dive */}
      <section className="py-24 md:py-32 px-6 lg:px-8 max-w-7xl mx-auto relative z-10 border-t border-white/5 bg-[#0A0A0F]">
        <div className="grid grid-cols-1 lg:grid-cols-2 gap-16 items-center">
          <div>
            <div className="inline-flex items-center justify-center mb-6">
              <span className="bg-[#FF7778]/10 text-[#FF7778] border border-[#FF7778]/20 text-[10px] uppercase font-medium tracking-widest px-4 py-1.5 rounded-full shadow-sm">The Psychographic Engine</span>
            </div>
            <h2 className="text-4xl md:text-5xl font-light font-display text-white mb-6 leading-tight">
              Why generic AI copy <span className="text-[#FF7778]">destroys your brand.</span>
            </h2>
            <div className="space-y-6 text-gray-400 font-light leading-relaxed">
              <p>
                The problem with "AI Writers" isn't the LLM. It's the prompt. Asking a chatbot to "write a LinkedIn post about SaaS" results in generic platitudes that actively harm your credibility.
              </p>
              <p>
                To write high-converting copy, you need root-level psychographics: <strong>The exact pain your customer is in, the "Hell State" they want to escape, and the Unique Mechanism your product uses to save them.</strong>
              </p>
              <p>
                Tror’s Strategist Agent doesn't just read your website; it extracts a 12-point psychographic profile, locking in your exact "Heaven State," "Hell State," and Top Objections before a single word is drafted. This is why Tror's output reads like a Senior Copywriter, not a robot.
              </p>
            </div>
          </div>
          
          <div className="relative">
            <div className="absolute inset-0 bg-[#FF7778]/10 blur-[100px] rounded-full pointer-events-none"></div>
            <div className="glass-card p-8 border-[#FF7778]/20 relative z-10">
              <div className="flex items-center justify-between mb-6 pb-6 border-b border-white/5">
                <div className="flex items-center gap-3">
                  <Database className="w-5 h-5 text-[#FF7778]" />
                  <span className="text-sm font-medium text-white">Brand DNA Matrix</span>
                </div>
                <span className="text-xs text-[#18F07A]">LOCKED</span>
              </div>
              
              <div className="space-y-5">
                <div className="bg-[#1C1C22]/80 p-4 rounded-lg border border-white/5">
                   <div className="text-[10px] text-gray-500 uppercase tracking-widest mb-1 font-medium">Hell State identified</div>
                   <div className="text-sm text-gray-200 font-light">"Endless manual spreadsheet reconciliation leading to 4am fire drills."</div>
                </div>
                <div className="bg-[#1C1C22]/80 p-4 rounded-lg border border-white/5">
                   <div className="text-[10px] text-gray-500 uppercase tracking-widest mb-1 font-medium">Unique Mechanism identified</div>
                   <div className="text-sm text-gray-200 font-light">"Asynchronous multi-ledger sync using proprietary WebAssembly core."</div>
                </div>
                <div className="bg-[#1C1C22]/80 p-4 rounded-lg border border-white/5 border-l-2 border-l-[#FF7778]">
                   <div className="text-[10px] text-gray-500 uppercase tracking-widest mb-1 font-medium">Objection Dismantling Strategy</div>
                   <div className="text-sm text-gray-200 font-light">"Injecting SOC2 compliance proof in hook 3 to counter security fears."</div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>


      {/* POST Methodology */}
      <section className="py-24 md:py-32 px-6 lg:px-8 max-w-7xl mx-auto relative z-10">
        <div className="text-center mb-16">
          <div className="inline-flex items-center justify-center mb-4">
            <span className="bg-[#7C3AED]/10 text-[#7C3AED] border border-[#7C3AED]/20 text-xs font-medium uppercase tracking-widest px-4 py-1.5 rounded-full shadow-sm">The Engine Under The Hood</span>
          </div>
          <h2 className="text-5xl md:text-6xl font-normal font-display text-white mb-6">
            Execute the <span className="text-[#7C3AED]">POST Framework</span> automatically.
          </h2>
          <p className="text-lg text-gray-400 max-w-2xl mx-auto font-medium leading-relaxed">
            We don't do random virality. Our entire agentic system is designed to execute the rigorous POST methodology proven by top B2B and Consumer brands.
          </p>
        </div>
        
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6">
          {[
            { l: "P", t: "Position", d: "Solidify your narrative. We extract and lock your DNA so every generated output reinforces your actual value prop.", c: "bg-[#1C1C22]", br: "border-[#7C3AED]/30", icon: <Target className="h-6 w-6 text-[#7C3AED]"/> },
            { l: "O", t: "Outreach", d: "Distribute natively. Tror understands constraints, formats uniquely for LinkedIn vs Twitter, and deploys contextually.", c: "bg-[#1C1C22]", br: "border-[#2583EB]/30", icon: <Megaphone className="h-6 w-6 text-[#2583EB]"/> },
            { l: "S", t: "Signal", d: "Inject visual trust. Our engine ties visual data and branding cues directly to the copy, asserting category leadership.", c: "bg-[#1C1C22]", br: "border-[#FFFFFF]/30", icon: <Sparkles className="h-6 w-6 text-[#FFFFFF]"/> },
            { l: "T", t: "Traction", d: "Publish automatically. Approve your scheduled week in 1 click and let BrandToPost turn attention into pipeline.", c: "bg-[#1C1C22]", br: "border-[#18F07A]/30", icon: <TrendingUp className="h-6 w-6 text-[#18F07A]"/> }
          ].map((item, idx) => (
            <div key={idx} className={`rounded-[2rem] p-8 border ${item.br} ${item.c} shadow-[0_10px_40px_rgba(0,0,0,0.5)] relative overflow-hidden group hover:scale-[1.02] transition-transform`}>
              <div className="absolute top-0 right-0 w-32 h-32 bg-white/5 rounded-full blur-[40px] -mr-10 -mt-10 group-hover:bg-white/10 transition-colors"></div>
              <div className="relative z-10 flex flex-col h-full">
                <div className="flex justify-between items-start mb-8">
                  <div className={`w-14 h-14 rounded-2xl bg-[#0A0A0F]/80 backdrop-blur border ${item.br} flex justify-center items-center shadow-lg relative`}>
                    {item.icon}
                  </div>
                  <span className="text-6xl font-normal font-display text-white/[0.03] select-none">{item.l}</span>
                </div>
                <div>
                  <h3 className="text-2xl font-medium text-white mb-3">{item.t}</h3>
                  <p className="text-gray-400 text-sm font-medium leading-relaxed">{item.d}</p>
                </div>
              </div>
            </div>
          ))}
        </div>
      </section>

      

{/* Deep Dive: The Output */}
      <section className="py-24 px-6 lg:px-8 max-w-7xl mx-auto relative z-10 border-t border-white/5">
        <div className="text-center mb-16">
          <div className="inline-flex items-center justify-center mb-4">
            <span className="bg-[#18F07A]/10 text-[#18F07A] border border-[#18F07A]/20 text-[10px] uppercase font-medium tracking-widest px-4 py-1.5 rounded-full shadow-sm">The Deliverable</span>
          </div>
          <h2 className="text-4xl md:text-5xl font-light font-display text-white mb-6">
            1 URL in. 1 Month of <span className="text-[#18F07A]">Pipeline</span> out.
          </h2>
          <p className="text-lg text-gray-400 max-w-2xl mx-auto font-light leading-relaxed">
            We don't sell you "prompts" or "ai writing assistants." Tror’s agents architect, draft, and assemble a complete, multi-platform publishing engine tailored exactly to your user’s pain points.
          </p>
        </div>

        <div className="grid grid-cols-1 md:grid-cols-3 gap-6 max-w-5xl mx-auto">
          {/* Bento 1: LinkedIn Mastery */}
          <div className="glass-card p-8 md:col-span-2 relative overflow-hidden group">
            <div className="absolute top-0 right-0 w-64 h-64 bg-[#2583EB]/10 blur-[80px] rounded-full pointer-events-none group-hover:bg-[#2583EB]/20 transition-all"></div>
            <h3 className="text-2xl text-white font-light mb-2">12x LinkedIn Thought Leadership Posts</h3>
            <p className="text-gray-400 font-light mb-8 text-sm leading-relaxed max-w-md">Crafted by the Copywriter agent using the hook-story-lesson framework. Formatted with proper spacing, strategic zero-click methodology, and your exact brand tone.</p>
            
            <div className="bg-[#1C1C22]/80 border border-white/5 rounded-xl p-6 relative z-10 shadow-lg">
              <div className="flex gap-4 mb-4">
                <div className="w-10 h-10 rounded-full bg-[#7C3AED]"></div>
                <div>
                  <div className="w-32 h-2 bg-white/20 rounded mb-2"></div>
                  <div className="w-20 h-2 bg-white/10 rounded"></div>
                </div>
              </div>
              <div className="space-y-2">
                <div className="w-full h-2 bg-white/20 rounded"></div>
                <div className="w-[90%] h-2 bg-white/20 rounded"></div>
                <div className="w-[80%] h-2 bg-white/20 rounded"></div>
              </div>
            </div>
          </div>

          {/* Bento 2: Native X Threads */}
          <div className="glass-card p-8 relative overflow-hidden group">
            <div className="absolute top-0 right-0 w-64 h-64 bg-[#7C3AED]/10 blur-[80px] rounded-full pointer-events-none group-hover:bg-[#7C3AED]/20 transition-all"></div>
            <h3 className="text-2xl text-white font-light mb-2">20x Native X Threads</h3>
            <p className="text-gray-400 font-light mb-8 text-sm leading-relaxed">Punchy, visually segmented threads optimized for the X algorithm.</p>
            <div className="space-y-4">
              {[1,2,3].map(i => (
                <div key={i} className="flex gap-3 items-start border-l-2 border-white/10 pl-4 py-1">
                   <div className="w-6 h-6 rounded-full bg-white/10 shrink-0"></div>
                   <div className="w-full h-8 bg-white/5 rounded"></div>
                </div>
              ))}
            </div>
          </div>

          {/* Bento 3: DNA Verification */}
          <div className="glass-card p-8 relative overflow-hidden group">
             <h3 className="text-2xl text-white font-light mb-2">Brand DNA Report</h3>
             <p className="text-gray-400 font-light mb-6 text-sm leading-relaxed">The Strategist locks down your ICP and unique mechanism.</p>
             <div className="flex flex-wrap gap-2">
               <span className="px-3 py-1 bg-white/5 border border-white/10 rounded-full text-[10px] uppercase tracking-wider text-white/70">Value Prop</span>
               <span className="px-3 py-1 bg-white/5 border border-white/10 rounded-full text-[10px] uppercase tracking-wider text-white/70">Tone Tracker</span>
               <span className="px-3 py-1 bg-white/5 border border-white/10 rounded-full text-[10px] uppercase tracking-wider text-white/70">Competitor Map</span>
             </div>
          </div>

          {/* Bento 4: Visual Hooks */}
          <div className="glass-card p-8 md:col-span-2 relative overflow-hidden group flex flex-col md:flex-row items-center gap-8">
             <div className="flex-1">
               <h3 className="text-2xl text-white font-light mb-2">High-Fidelity Visual Hooks</h3>
               <p className="text-gray-400 font-light text-sm leading-relaxed">The Designer agent creates branded UI mockups and infographics to stop the scroll. Always aligned with your actual interface and brand parameters.</p>
             </div>
             <div className="w-full md:w-48 h-32 md:h-48 rounded-xl bg-[#1C1C22] border border-white/10 flex items-center justify-center shadow-inner relative overflow-hidden">
                <div className="absolute inset-0 bg-[#0A0A0F] opacity-50"></div>
                <div className="w-20 h-20 rounded shadow-lg bg-white/10 backdrop-blur-md border border-white/20 relative z-10 flex items-center justify-center">
                  <div className="w-8 h-8 rounded-full bg-[#18F07A]"></div>
                </div>
             </div>
          </div>
        </div>
      </section>


      

{/* Visual Agents Architecture */}
      <section className="py-24 md:py-32 px-6 lg:px-8 max-w-7xl mx-auto relative z-10 border-t border-white/5">
        <div className="text-center mb-16">
          <div className="inline-flex items-center justify-center mb-4">
            <span className="bg-[#7C3AED]/10 text-[#7C3AED] border border-[#7C3AED]/20 text-xs font-medium uppercase tracking-widest px-4 py-1.5 rounded-full shadow-sm">Autonomous Architecture</span>
          </div>
          <h2 className="text-4xl md:text-5xl font-normal font-display text-white mb-6">4 Specialized Agents.<br/>1 CMO Orchestrating Them.</h2>
          <p className="text-lg text-gray-400 max-w-2xl mx-auto font-medium leading-relaxed">
            You aren't just buying software. You are hiring a complete marketing department that executes your strategy simultaneously.
          </p>
        </div>

        <div className="relative max-w-5xl mx-auto mt-20">
          {/* Tror Node */}
          <div className="flex flex-col items-center relative z-20 mb-8 sm:mb-16">
            <div className="w-24 h-24 sm:w-28 sm:h-28 rounded-[2rem] bg-[#7C3AED] p-[2px] shadow-[0_0_40px_rgba(124,58,237,0.4)] relative">
               <div className="w-full h-full bg-[#1C1C22] rounded-[30px] flex flex-col items-center justify-center p-2 relative overflow-hidden">
                  <div className="absolute inset-0 bg-[#7C3AED]/20 animate-pulse"></div>
                  <img src="https://darkgray-finch-838850.hostingersite.com/wp-content/uploads/2026/04/B2P-AVATAR.png" alt="Tror" className="w-12 h-12 sm:w-14 sm:h-14 rounded-full relative z-10 border border-white/20"/>
               </div>
            </div>
            <div className="mt-6 text-center bg-[#1C1C22]/80 backdrop-blur-md px-6 py-3 rounded-full border border-white/10 shadow-xl">
              <h3 className="text-xl font-medium text-white mb-0.5">Tror</h3>
              <p className="text-xs font-medium text-[#7C3AED] uppercase tracking-wider">The Orchestrator</p>
            </div>
          </div>

          {/* Connecting lines for Desktop */}
          <div className="hidden lg:block absolute top-[110px] left-1/2 -translate-x-1/2 w-[75%] h-[80px] border-t-2 border-l-2 border-r-2 border-dashed border-[#7C3AED]/40 rounded-t-3xl z-10">
             {/* Center pulsing line from Tror */}
             <div className="absolute top-0 left-1/2 w-0.5 h-16 bg-[#7C3AED]/40 -translate-x-1/2 -mt-4 animate-pulse"></div>
          </div>

          {/* Agents Grid */}
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-8 lg:gap-6 relative z-20">
            
            {/* Agent 1 */}
            <div className="glass-card p-8 flex flex-col items-center text-center relative group hover:-translate-y-2 transition-transform duration-300">
              <div className="hidden lg:block absolute -top-20 left-1/2 w-0.5 h-20 bg-[#FF7778]/40 -translate-x-1/2 opacity-0 group-hover:opacity-100 transition-opacity" />
              <div className="w-16 h-16 rounded-2xl bg-[#1C1C22] border border-[#FF7778]/30 flex items-center justify-center mb-6 relative shadow-[0_0_20px_rgba(255,119,120,0.1)] group-hover:shadow-[0_0_30px_rgba(255,119,120,0.3)] transition-all">
                 <BrainCircuit className="w-8 h-8 text-[#FF7778]" />
                 <div className="absolute -top-1 -right-1 w-3 h-3 bg-[#FF7778] rounded-full animate-pulse shadow-[0_0_10px_#FF7778]"></div>
              </div>
              <h3 className="text-lg font-medium text-white mb-2">The Strategist</h3>
              <p className="text-sm text-gray-400">Scrapes DNA, defines positioning, locks in the core value proposition.</p>
            </div>

            {/* Agent 2 */}
            <div className="glass-card p-8 flex flex-col items-center text-center relative group hover:-translate-y-2 transition-transform duration-300 transform lg:translate-y-8">
              <div className="hidden lg:block absolute -top-24 left-1/2 w-0.5 h-24 bg-[#2583EB]/40 -translate-x-1/2 opacity-0 group-hover:opacity-100 transition-opacity" />
              {/* Extra connecting line for staggered layout */}
              <div className="hidden lg:block absolute -top-8 left-1/2 w-0.5 h-8 border-l-2 border-dashed border-[#7C3AED]/40 -translate-x-1/2 z-10" />
              
              <div className="w-16 h-16 rounded-2xl bg-[#1C1C22] border border-[#2583EB]/30 flex items-center justify-center mb-6 relative shadow-[0_0_20px_rgba(37,131,235,0.1)] group-hover:shadow-[0_0_30px_rgba(37,131,235,0.3)] transition-all">
                 <PenTool className="w-8 h-8 text-[#2583EB]" />
                 <div className="absolute -top-1 -right-1 w-3 h-3 bg-[#2583EB] rounded-full animate-pulse shadow-[0_0_10px_#2583EB]"></div>
              </div>
              <h3 className="text-lg font-medium text-white mb-2">The Copywriter</h3>
              <p className="text-sm text-gray-400">Drafts emotionally resonant, native formats for LinkedIn and X.</p>
            </div>

            {/* Agent 3 */}
            <div className="glass-card p-8 flex flex-col items-center text-center relative group hover:-translate-y-2 transition-transform duration-300 transform lg:translate-y-8">
              <div className="hidden lg:block absolute -top-24 left-1/2 w-0.5 h-24 bg-[#18F07A]/40 -translate-x-1/2 opacity-0 group-hover:opacity-100 transition-opacity" />
              {/* Extra connecting line for staggered layout */}
              <div className="hidden lg:block absolute -top-8 left-1/2 w-0.5 h-8 border-l-2 border-dashed border-[#7C3AED]/40 -translate-x-1/2 z-10" />
              
              <div className="w-16 h-16 rounded-2xl bg-[#1C1C22] border border-[#18F07A]/30 flex items-center justify-center mb-6 relative shadow-[0_0_20px_rgba(24,240,122,0.1)] group-hover:shadow-[0_0_30px_rgba(24,240,122,0.3)] transition-all">
                 <Palette className="w-8 h-8 text-[#18F07A]" />
                 <div className="absolute -top-1 -right-1 w-3 h-3 bg-[#18F07A] rounded-full animate-pulse shadow-[0_0_10px_#18F07A]"></div>
              </div>
              <h3 className="text-lg font-medium text-white mb-2">The Designer</h3>
              <p className="text-sm text-gray-400">Generates branded assets and hooks matched to the drafted copy.</p>
            </div>

            {/* Agent 4 */}
            <div className="glass-card p-8 flex flex-col items-center text-center relative group hover:-translate-y-2 transition-transform duration-300">
              <div className="hidden lg:block absolute -top-20 left-1/2 w-0.5 h-20 bg-[#7C3AED]/40 -translate-x-1/2 opacity-0 group-hover:opacity-100 transition-opacity" />
              <div className="w-16 h-16 rounded-2xl bg-[#1C1C22] border border-[#7C3AED]/30 flex items-center justify-center mb-6 relative shadow-[0_0_20px_rgba(124,58,237,0.1)] group-hover:shadow-[0_0_30px_rgba(124,58,237,0.3)] transition-all">
                 <Send className="w-8 h-8 text-[#7C3AED]" />
                 <div className="absolute -top-1 -right-1 w-3 h-3 bg-[#7C3AED] rounded-full animate-pulse shadow-[0_0_10px_#7C3AED]"></div>
              </div>
              <h3 className="text-lg font-medium text-white mb-2">The Distributor</h3>
              <p className="text-sm text-gray-400">Assembles outputs into a final approval queue, ready to publish.</p>
            </div>

          </div>
        </div>
      </section>


      

{/* Feature 2: Tror Generation - REDESIGNED */}
      <section className="py-24 md:py-32 px-6 lg:px-8 max-w-7xl mx-auto relative z-10 border-t border-white/5 bg-[#0A0A0F]">
        <div className="flex flex-col-reverse lg:flex-row items-center gap-12 lg:gap-20">
          <div className="flex-1 w-full flex justify-center lg:justify-start">
             <TrorCommandCenterMockup />
          </div>
          <div className="flex-1 space-y-6">
            <div className="w-14 h-14 rounded-2xl bg-[#1C1C22] border border-white/10 flex items-center justify-center shadow-lg mb-8 relative">
               <Bot className="w-7 h-7 text-[#2583EB]" />
               <div className="absolute top-2 right-2 w-2 h-2 bg-[#18F07A] rounded-full animate-pulse shadow-[0_0_10px_#18F07A]"></div>
            </div>
            <h2 className="text-5xl md:text-6xl font-normal font-display text-white tracking-tight leading-[1.1]">Tror: The Orchestrator<br/>of <span className="text-[#2583EB]">Your New Team.</span></h2>
            <p className="text-lg text-gray-400 font-medium leading-relaxed">
              Meet Tror. He isn't just an agent; he's the CMO. He doesn't just run prompts; he manages the agents. He routes the web-scraped data to the Strategist, passes the brief to the Copywriter, coordinates with the Designer, and hands you the finished campaign before your morning coffee. 
            </p>
            <ul className="space-y-3 pt-2">
               <li className="flex gap-2 items-center text-gray-300 font-medium"><CheckCircle2 className="w-4 h-4 text-[#2583EB]" /> Live Web & Competitor Research</li>
               <li className="flex gap-2 items-center text-gray-300 font-medium"><CheckCircle2 className="w-4 h-4 text-[#2583EB]" /> Multi-Agent Orchestration</li>
               <li className="flex gap-2 items-center text-gray-300 font-medium"><CheckCircle2 className="w-4 h-4 text-[#2583EB]" /> Platform-Native Asset Generation</li>
            </ul>
          </div>
        </div>
      </section>

      {/* Dashboard Showcase */}
      <section className="py-24 md:py-32 px-6 lg:px-8 max-w-7xl mx-auto relative z-10 border-t border-white/5 bg-[#0A0A0F]">
        <div className="text-center mb-8">
          <div className="inline-flex items-center justify-center mb-4">
            <span className="bg-[#7C3AED]/10 text-[#7C3AED] border border-[#7C3AED]/20 text-[10px] uppercase font-medium tracking-widest px-4 py-1.5 rounded-full shadow-sm">Command Center</span>
          </div>
          <h2 className="text-4xl md:text-5xl font-normal font-display text-white mb-6">
            Review and deploy with <span className="text-[#7C3AED]">One Click.</span>
          </h2>
          <p className="text-lg text-gray-400 max-w-2xl mx-auto font-medium leading-relaxed">
            Your entire 30-day strategy plotted out in an intuitive workspace. Approve the week, edit natively, or let Tror publish on your behalf.
          </p>
        </div>
        <HeroDashboardMockup />
      </section>

{/* CTA Section */}
      <section className="py-32 px-6 lg:px-8 relative overflow-hidden z-10">
        <div className="absolute inset-0 bg-[#7C3AED]/5 pointer-events-none" />
        <div className="max-w-4xl mx-auto text-center relative z-10 bg-[#1C1C22]/80 backdrop-blur-2xl border border-white/10 rounded-[3rem] p-12 md:p-24 shadow-[0_40px_100px_rgba(124,58,237,0.15)] overflow-hidden">
          <div className="absolute inset-0 bg-[#7C3AED]/5 pointer-events-none"></div>
          
          <div className="flex justify-center mb-8 relative">
             <div className="absolute inset-0 bg-[#7C3AED]/30 blur-[40px] rounded-full w-32 h-32 mx-auto"></div>
             <img src="https://darkgray-finch-838850.hostingersite.com/wp-content/uploads/2026/04/B2P-AVATAR.png" alt="Tror" className="w-24 h-24 rounded-full border-4 border-[#1C1C22] shadow-[0_0_40px_rgba(124,58,237,0.6)] relative z-10" />
          </div>
          <h2 className="text-5xl md:text-7xl font-normal font-display text-white mb-6 tracking-tight">Get your 20 hours<br/>a week back.</h2>
          <p className="text-xl text-gray-400 mb-12 max-w-2xl mx-auto font-medium leading-relaxed">Join the next wave of founders who treat organic social not as a chore, but as a fully automated, highly capable revenue engine.</p>
          <div className="flex flex-col justify-center gap-4">
            <a 
              href={isDefaultWhatsAppUrl ? "#" : whatsappUrl} 
              onClick={(e) => {
                if (isDefaultWhatsAppUrl) {
                  e.preventDefault();
                  setShowSetupModal(true);
                }
              }}
              {...(!isDefaultWhatsAppUrl && whatsappUrl.startsWith("http") ? { target: "_blank", rel: "noreferrer" } : {})}
              className="inline-flex items-center justify-center gap-3 text-white px-10 py-5 rounded-full text-lg font-medium transition-all hover:scale-105 active:scale-95 bg-[#00A884] hover:bg-[#008f70] shadow-[0_0_50px_rgba(37,211,102,0.4)] mx-auto cursor-pointer"
            >
              💬 Deploy Tror On WhatsApp Now <ArrowRight className="h-6 w-6" />
            </a>
            <span className="text-sm text-gray-500 mt-2 font-medium">Instantly onboard your local business in under 60 seconds.</span>
          </div>
        </div>
      </section>

      

      {/* Footer */}
      <footer className="border-t border-white/5 py-12 px-6 bg-[#0A0A0F] relative z-10">
        <div className="max-w-7xl mx-auto flex flex-col md:flex-row justify-between items-center gap-6 text-sm font-medium text-gray-500">
           <div className="flex items-center gap-3">
             <div className="w-10 h-10 rounded-xl bg-[#1C1C22] border border-white/10 flex items-center justify-center overflow-hidden opacity-90 transition-opacity hover:opacity-100">
                <img src="https://darkgray-finch-838850.hostingersite.com/wp-content/uploads/2026/04/B2PLOGO.png" className="w-6 h-6 object-contain" alt="logo"/>
             </div>
             <span className="font-medium text-gray-300 font-display text-lg tracking-tight">BrandToPost</span>
           </div>
           <div className="flex gap-8">
             <span className="hover:text-white transition-colors cursor-pointer font-semibold">Manifesto</span>
             <span className="hover:text-white transition-colors cursor-pointer font-semibold">Twitter</span>
           </div>
           <p className="font-medium">&copy; {new Date().getFullYear()} BrandToPost Systems. Automatic pipeline generation.</p>
        </div>
      </footer>

      {/* WhatsApp Quick Setup Overlay Modal */}
      {showSetupModal && (
        <div className="fixed inset-0 z-[100] flex items-center justify-center p-4">
          <div className="absolute inset-0 bg-[#060608]/90 backdrop-blur-md" onClick={() => setShowSetupModal(false)}></div>
          
          <div className="relative bg-[#111115] border border-white/10 rounded-[30px] w-full max-w-lg p-8 shadow-[0_20px_50px_rgba(0,168,132,0.15)] overflow-hidden animate-in fade-in zoom-in duration-250">
            <div className="absolute top-0 right-0 p-4">
              <button 
                onClick={() => setShowSetupModal(false)}
                className="text-gray-400 hover:text-white transition-colors cursor-pointer w-8 h-8 rounded-full bg-white/5 flex items-center justify-center"
              >
                <X className="w-5 h-5" />
              </button>
            </div>

            <div className="flex flex-col items-center text-center mt-2 relative">
              <div className="w-16 h-16 rounded-2xl bg-[#00A884]/15 border border-[#00A884]/30 flex items-center justify-center text-[#00A884] mb-6 shadow-xl">
                <MessageSquare className="w-8 h-8 animate-pulse" />
              </div>

              <h3 className="text-2xl font-semibold font-display text-white tracking-tight">🔗 Link Your Onboarding Bot</h3>
              <p className="text-sm text-gray-400 mt-2 max-w-sm leading-relaxed">
                To onboard your client businesses directly through your WhatsApp App, link your live WhatsApp phone number below.
              </p>

              {linkSuccess ? (
                <div className="mt-8 p-6 bg-[#00A884]/10 border border-[#00A884]/30 text-[#00A884] rounded-2xl w-full flex flex-col items-center gap-2 animate-pulse">
                  <CheckCircle2 className="w-8 h-8 animate-bounce shrink-0" />
                  <span className="text-sm font-semibold font-sans">Verification Successful!</span>
                  <span className="text-xs text-emerald-400/70">Opening WhatsApp Messenger...</span>
                </div>
              ) : (
                <form onSubmit={handleQuickSetupInput} className="mt-8 w-full space-y-4">
                  <div className="text-left font-sans">
                    <label className="block text-xs font-semibold text-gray-300 uppercase tracking-wider mb-2">WhatsApp Phone Number</label>
                    <input
                      type="text"
                      required
                      placeholder="e.g. 919876543210"
                      value={botPhoneNumberInput}
                      onChange={(e) => setBotPhoneNumberInput(e.target.value)}
                      className="w-full bg-[#181820] border border-white/10 rounded-2xl px-4 py-3.5 text-sm text-white placeholder-gray-500 focus:outline-none focus:border-[#00A884]/70 transition-colors"
                    />
                    <p className="text-[10px] text-gray-500 mt-1.5 leading-relaxed">
                      Only input numbers with country code. Do not include spaces, +, brackets or dashes (e.g. use <strong>919876543210</strong>, not +91 98765-43210).
                    </p>
                  </div>

                  {linkError && (
                    <div className="text-xs text-rose-400 text-left bg-rose-500/10 border border-rose-500/20 px-3.5 py-2.5 rounded-xl font-sans">
                      {linkError}
                    </div>
                  )}

                  <button
                    type="submit"
                    disabled={isLinking}
                    className="w-full inline-flex items-center justify-center gap-2.5 text-white font-semibold py-3.5 px-6 rounded-2xl bg-[#00A884] hover:bg-[#008f70] shadow-md transition-all active:scale-95 disabled:opacity-50 disabled:pointer-events-none cursor-pointer font-sans"
                  >
                    {isLinking ? (
                      <>
                        <Loader2 className="w-5 h-5 animate-spin" />
                        <span>Linking Bot...</span>
                      </>
                    ) : (
                      <>
                        <Zap className="w-4 h-4 fill-white animate-bounce" />
                        <span>Activate & Launch Tror Bot</span>
                      </>
                    )}
                  </button>
                </form>
              )}
            </div>
          </div>
        </div>
      )}
    </div>
  );
}
