import React from 'react';
import { Link } from 'react-router-dom';
import { ArrowLeft } from 'lucide-react';

export function TermsOfService() {
  return (
    <div className="min-h-screen bg-[#FAF9F6] text-slate-800 font-sans selection:bg-[#7C3AED]/10 selection:text-[#7C3AED] py-16 px-6 lg:px-8">
      {/* Small Header */}
      <header className="max-w-7xl mx-auto w-full mb-16">
        <Link 
          to="/" 
          className="inline-flex items-center gap-2 text-xs font-semibold text-slate-500 hover:text-slate-900 transition-colors uppercase tracking-wider"
        >
          <ArrowLeft className="w-3.5 h-3.5" />
          <span>Back to home</span>
        </Link>
      </header>

      {/* Main Content Layout */}
      <main className="max-w-7xl mx-auto w-full">
        <div className="grid grid-cols-1 lg:grid-cols-10 gap-12 lg:gap-16 items-start">
          
          {/* Left Column - Metadata & Sidebar */}
          <div className="lg:col-span-3 flex flex-col gap-6 lg:sticky lg:top-8">
            <span className="font-mono text-[10px] tracking-widest text-[#7C3AED] uppercase font-semibold">Legal Registry</span>
            <h1 className="text-3xl sm:text-4xl font-light tracking-tight text-slate-900 leading-tight">
              Terms of <br className="hidden lg:inline" />Service.
            </h1>
            <p className="text-xs text-slate-400 font-light font-mono">
              Last Updated: July 05, 2026
            </p>
            <div className="border-t border-slate-900/10 pt-6 mt-2 hidden lg:flex flex-col gap-3 text-xs text-slate-400">
              <p className="font-light leading-relaxed">
                By activating a subscription node, you agree to these operating parameters.
              </p>
              <p className="font-light leading-relaxed">
                All platform processes are managed by our core orchestration engines.
              </p>
            </div>
          </div>

          {/* Right Column - Terms Content */}
          <div className="lg:col-span-7 flex flex-col gap-12 font-light text-slate-600 text-sm leading-relaxed font-sans">
            
            {/* Section 1 */}
            <div className="flex flex-col gap-4">
              <h2 className="text-sm font-semibold text-slate-900 tracking-wider uppercase font-sans">
                1. System Initialization & Roster Access
              </h2>
              <div className="flex flex-col gap-3">
                <p>
                  BrandToPost grants you access to an autonomous posting network. This network operates through specialized agent nodes designed for specific B2B publication tasks.
                </p>
                <p>
                  By deploying a node, you authorize our roster to analyze your business profiles. This roster includes Sarah (Research), Alex (Copywriting), and Chloe (Visual Design).
                </p>
              </div>
            </div>

            {/* Section 2 */}
            <div className="border-t border-slate-900/10 pt-8 flex flex-col gap-4">
              <h2 className="text-sm font-semibold text-slate-900 tracking-wider uppercase font-sans">
                2. Brand Context & Integration Data
              </h2>
              <div className="flex flex-col gap-3">
                <p>
                  Our agent nodes function by constructing a persistent digital profile of your business. This profile is built using your onboarding inputs and public marketing assets.
                </p>
                <p>
                  You are responsible for ensuring the accuracy of all context files provided. If you supply misleading guidelines, the outputs produced by our copywriters may not align with your targets.
                </p>
              </div>
            </div>

            {/* Section 3 */}
            <div className="border-t border-slate-900/10 pt-8 flex flex-col gap-4">
              <h2 className="text-sm font-semibold text-slate-900 tracking-wider uppercase font-sans">
                3. Content Ownership & Production Rights
              </h2>
              <div className="flex flex-col gap-3">
                <p>
                  All copy generated by Alex, visual structures created by Chloe or Julian, and synthetic outputs from Arthur remain accessible to you. You hold publishing rights to all final outputs.
                </p>
                <p>
                  We retain all rights to the underlying agent architectures, prompt mechanics, and visual generation engines. You may not reverse-engineer or extract the model parameters.
                </p>
              </div>
            </div>

            {/* Section 4 */}
            <div className="border-t border-slate-900/10 pt-8 flex flex-col gap-4">
              <h2 className="text-sm font-semibold text-slate-900 tracking-wider uppercase font-sans">
                4. Automated Scheduling & Platform Limits
              </h2>
              <div className="flex flex-col gap-3">
                <p>
                  The platform schedules and publishes updates to your social accounts automatically. We queue these items based on performance schedules designed by our engines.
                </p>
                <p>
                  We are not responsible for direct network downtime or API suspensions by third-party social platforms. We adjust posting volume dynamically to comply with rate limits.
                </p>
              </div>
            </div>

            {/* Section 5 */}
            <div className="border-t border-slate-900/10 pt-8 flex flex-col gap-4">
              <h2 className="text-sm font-semibold text-slate-900 tracking-wider uppercase font-sans">
                5. Subscription Nodes & Cancellation
              </h2>
              <div className="flex flex-col gap-3">
                <p>
                  Subscriptions are billed on a recurring monthly or annual cycle. You can cancel your subscription plan directly from your settings panel.
                </p>
                <p>
                  Upon cancellation, your custom database profile is decommissioned within thirty days. Active post drafts generated during your cycle will remain archived for retrieval.
                </p>
              </div>
            </div>

            {/* Section 6 */}
            <div className="border-t border-slate-900/10 pt-8 flex flex-col gap-4">
              <h2 className="text-sm font-semibold text-slate-900 tracking-wider uppercase font-sans">
                6. Liability & Service Limits
              </h2>
              <div className="flex flex-col gap-3">
                <p>
                  The system is provided on an "as-is" basis without warranties of any kind. BrandToPost is not liable for business loss or engagement drops caused by automated drafts.
                </p>
                <p>
                  We reserve the right to suspend any account that submits offensive context files or aims to distribute spam.
                </p>
              </div>
            </div>

          </div>

        </div>
      </main>

      {/* Small Footer */}
      <footer className="max-w-7xl mx-auto w-full border-t border-slate-900/10 mt-16 pt-8 flex flex-col sm:flex-row justify-between items-center gap-4 text-xs text-slate-400">
        <p className="font-light font-mono text-[10px]">
          &copy; {new Date().getFullYear()} BrandToPost Systems. All rights reserved.
        </p>
        <div className="flex gap-6 font-light font-mono text-[10px]">
          <Link to="/privacy" className="hover:text-slate-900 transition-colors">Privacy Policy</Link>
          <span className="text-slate-200">/</span>
          <span className="text-slate-600">Terms of Service</span>
        </div>
      </footer>
    </div>
  );
}
